name: "Debug with ssh"
description: "This GitHub Action enables direct interaction with the host system running your GitHub Actions via SSH"
author: "Owen Ou"
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "node20"
  main: "lib/index.js"
inputs:
  limit-access-to-actor:
    description: "If only the public SSH keys of the user triggering the workflow should be authorized"
    required: false
    default: "false"
  limit-access-to-users:
    description: "If only the public SSH keys of the listed GitHub users should be authorized"
    required: false
    default: ""
  upterm-server:
    description: "upterm server address (required), supported protocols are ssh, ws, or wss."
    required: true
    default: "ssh://uptermd.upterm.dev:22"
  ssh-known-hosts:
    description: "Content for ~/.ssh/known_hosts file on the server"
    required: false
    default: ""
  wait-timeout-minutes:
    description: "Integer number of minutes to wait for user to connect before shutting down server. Once a user connects, the server will stay up."
    required: false
    default: ""
  upterm-error-is-failure:
    description: "When upterm fails to start and/or connect to the upterm server, fail the action."
    type: boolean
    required: true
    default: true
